package com.us.fusion7
import com.us.person.Person

function void printName(String streamName,String name,int age,String desc) {
            System.out.println("streamName:"+streamName+"  name:"+name+" age:"+age+" desc:"+ desc);

        }


declare Person
    @role( event )
    @expires( 1s )
end
         rule "boy"
            salience 1
            when
                $p : Person(age > 0) over window:time( 10s )
            then
                $p.setDesc("少年");
                $p.setAge($p.getAge()+$p.getAge());
                retract($p);
                printName("boy",$p.getName(),$p.getAge(),$p.getDesc());
        end

//        rule "youth"
//            salience 2
//            when
//                $p : Person(age > 12) from entry-point "youth";
//            then
//                $p.setDesc("青年");
//                retract($p);
//                printName("youth",$p.getName(),$p.getDesc());
//        end

//        rule "ageSum"
//            salience 2
//            when
////                $p : Person(age > 0) over window:length(2) from entry-point "ageSum";
//                  $p : Person(age > 0) over window:length(2);
//            then
//                $p.setAge($p.getAge()+$p.getAge());
//                printName("ageAverage",$p.getName(),$p.getAge()+"");
//                retract($p);
//        end
